spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: HKhk61+-
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 5555