spring:
  application:
    name: EurekaServer  # Config Server'dan alınacak yapılandırma dosyasının adı
  profiles:
    include: common  # common.yml dosyasını dahil et
  config:
    import: configserver:http://localhost:8888
