server:
  port: 8888  # Config Server'ın çalışacağı port

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          search-paths: config  # Repo içindeki yapılandırma dosyalarının bulunduğu klasör